### ISSUE TITLE
Production tab: unselect cities bought from after mass buy

### ISSUE THREAD

**Issue by lmoureaux** [Lexxie9952/fcw.org-server#19]
They remain selected, and if one doesn't unselect them by hand the message window gets cluttered with messages "you have already bought this turn"

**Comment by Lexxie9952** [comment]
ESC or space unselects.

Selection is not only a precursor toward a buying action. If it were, completion of buying should unselect all cities. However... One may want to remember which cities one bought in, in order to use this as a new selection mask. For example, to now toggle selection to all cities one did not buy in.
